### ISSUE TITLE
Installation is missing

### ISSUE THREAD

**Issue by EnergeticPixels** [Oluwasegun-AA/md-generator#35]
**Describe the bug**
According to instructions in README, a `npm install --global md-generator` should be all I need to install. Running md-generator gets a md-generator is not a file.

**To Reproduce**
1. npm install --global md-generator

**Expected behavior**
md-generator create --all should produce all standard markdown project related files in a directory.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Home (admin rights)
 - NodeJS: 16.13.2
 - NPM: 8.1.4

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Oluwasegun-AA** [comment]
Thank you for raising this @EnergeticPixels. 
This issue has been addressed and released in v5.2

Thanks.
