### ISSUE TITLE
Not installing latest version

### ISSUE THREAD

**Issue by Terule** [Oluwasegun-AA/md-generator#40]
**Describe the bug**
When i run npm to install the package it install 0.5.2 even with @latest flag

**To Reproduce**
1. npm install -g md-generator@latest 
2. md-generator -V

**Expected behavior**
md-generator command should show latest version 0.5.4

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Oluwasegun-AA** [comment]
This has been resolved as well. 🎉
