### ISSUE TITLE
ZSH problem with latest version

### ISSUE THREAD

**Issue by Terule** [Oluwasegun-AA/md-generator#41]
**Describe the bug**
When I upgrade from latest version (0.5.4) ZSH stops recognizing md-generator command (worked on 0.5.3)

**To Reproduce**
With 0.5.3 installed:
1. npm install -g md-generator@0.5.4
2. md-generator -V
3. ZSH stops recognizing md-generator command (command not found)

**Expected behavior**
Should work fine

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Oluwasegun-AA** [comment]
I have not been able to reproduce this with ZSH, I will assume that  [V0.6.1](https://www.npmjs.com/package/md-generator/v/0.6.1) resolved this.
