### ISSUE TITLE
md-generator not working

### ISSUE THREAD

**Issue by Terule** [Oluwasegun-AA/md-generator#42]
**Describe the bug**
Updated from 0.5.2 to 0.5.3 and I'm still having problems generating the files.

**To Reproduce**
1. Open project folder
2. md-generator create
3. go through prompt

**Expected behavior**
Files generated

**Screenshots**
![propts answered](https://user-images.githubusercontent.com/20166561/228554199-0095c527-b76a-4642-8851-237d08fb2086.png)
![error](https://user-images.githubusercontent.com/20166561/228554232-4c97f36a-8b14-4123-a600-fd9c8ed1080d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Oluwasegun-AA** [comment]
Thanks for flagging this @Terule , this was due to an issue with `mkdirp` (an external module). this has been resolved in version [0.6.1](https://www.npmjs.com/package/md-generator/v/0.6.1)
