### ISSUE TITLE
not setting default values on WLS

### ISSUE THREAD

**Issue by Terule** [Oluwasegun-AA/md-generator#44]
**Describe the bug**
Currently I'm using WSL to run Ubuntu 20.04 on windows and i thought the package was working as intended, but i installed it for a friend that uses ubuntu natively and I noticed that when he is generating the MD file, on homepage, md-generator suggests the repository link and for me on WSL it won't suggest anything. I don't know if it is because I'm running Linux on WLS or its simple a bug on my install. This behavior occurs on every option that suggest links like Homepage, issues etc.

**To Reproduce**
1. Open terminal and navigate to a cloned github project
2. md-generator create
3. select README.md
4. N for empty file
5. Yes, for HTML
6. ENTER, on project name (that has a suggestion)
7. ENTER, on project version (that has a suggestion)
8. Homepage don't have suggestion

**Expected behavior**
suggests project github links as default

**Screenshots**
![img1](https://user-images.githubusercontent.com/20166561/229285775-4ffeb432-5ce6-4df1-bcd5-56014be24784.png)
![img2](https://user-images.githubusercontent.com/20166561/229285796-c39fda19-5216-40b6-8537-752a9596fadb.png)
![img3](https://user-images.githubusercontent.com/20166561/229285812-b2f34fb1-6706-4ba7-bc85-d9964b948faf.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**
Noticed that the options that should have links suggested if left empty don't appear in the .md at all

**Comment by Terule** [comment]
Sorry to bother you so much. I loved this package and want to use it in my projects

**Comment by Oluwasegun-AA** [comment]
Hi @Terule,

This is the expected behaviour
The project detail suggestions are pulled from the `package.json` file, while the repository information is extracted from `Git`.
To ensure you get these suggestions, make sure :
- The directory has been initialised as a git project,
- the `package.json` file is exists and has all the required information

Cheers 🎉
